# Generated by Django 3.1.5 on 2021-06-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPupil',
            fields=[
                ('assign_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.user')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mark', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='marks',
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_archieved',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Assigned_pupil',
        ),
        migrations.AddField(
            model_name='grade',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.test'),
        ),
        migrations.AddField(
            model_name='grade',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.user'),
        ),
    ]
